# Generated by Django 5.0.2 on 2024-03-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maxcap',
            field=models.IntegerField(default=1),
        ),
    ]
