# Generated by Django 5.0.2 on 2024-03-16 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_maxcap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
