# Generated by Django 5.0.2 on 2024-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='realAttendee',
            field=models.IntegerField(default=0),
        ),
    ]
