# Generated by Django 5.0.2 on 2024-03-11 11:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PR_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homephone', models.CharField(blank=True, default='-', max_length=20)),
                ('cp', models.CharField(max_length=5)),
                ('nationalty', models.CharField(max_length=255)),
                ('personalPhoto', models.ImageField(default='personalPhoto/icon.png', upload_to='personalPhoto')),
                ('passportID', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PR_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfGuests', models.IntegerField(default=0)),
                ('hotelName', models.CharField(max_length=200, null=True)),
                ('hotelLocation', models.CharField(max_length=255, null=True)),
                ('nationaltyOfvisitors', models.CharField(max_length=255)),
                ('isApproved', models.IntegerField(default='-1')),
                ('notes', models.TextField(null=True)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
    ]
