# Generated by Django 5.0.2 on 2024-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_request',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
