# Generated by Django 5.0.2 on 2024-03-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_pr_profile_options_pr_profile_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_profile',
            name='homephone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
