# Generated by Django 5.0.2 on 2024-03-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_alter_pr_profile_homephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_profile',
            name='homephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
