# Generated by Django 5.0.2 on 2024-03-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_alter_pr_profile_homephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr_request',
            name='notes',
            field=models.TextField(default='لايوجد ملاحظات'),
        ),
    ]
