# Generated by Django 5.0.2 on 2024-03-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_pr_request_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr_profile',
            name='passportID',
        ),
    ]
